# Generated by Django 2.2.5 on 2019-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=200)),
                ('trail_length', models.FloatField()),
                ('trail_elevation', models.IntegerField()),
            ],
        ),
    ]
