# Generated by Django 2.2.5 on 2019-11-26 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bouy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcondition',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 26, 14, 7, 24, 942099, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
