# Generated by Django 2.2.5 on 2019-11-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouy', '0004_auto_20191126_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailwave',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
